defmodule Datos do
 def confeccionistas do
 [
 %{codigo: "C01", nombre: "María Elena Ríos", alquiler: true},
 %{codigo: "C02", nombre: "Andrés Salazar", alquiler: false},
 %{codigo: "C03", nombre: "Carlos Mendoza", alquiler: true},
 %{codigo: "C04", nombre: "Ana López", alquiler: false},
 %{codigo: "C05", nombre: "Luis García", alquiler: true},
 %{codigo: "C06", nombre: "Sara María", alquiler: false},
 %{codigo: "C07", nombre: "Miguel Ángel", alquiler: true},
 %{codigo: "C08", nombre: "Maria Fernanda", alquiler: false},
 %{codigo: "C09", nombre: "Silvana Ríos", alquiler: true},
 %{codigo: "C10", nombre: "Emanuel Franco", alquiler: false}

 ]
 end
 def lineas do
 [
 %{id: "L1", nombre: "Línea Norte", puestos: 6},
 %{id: "L2", nombre: "Línea Sur", puestos: 4}
 %{id: "L3", nombre: "Línea Este", puestos: 6},
 %{id: "L4", nombre: "Línea Oeste", puestos: 4}

 ]
 end
 def lotes do
 [

  #Lotes generados validos

    %{confeccionista: "C01", linea: "L1", dia: 1,
        prendas: 100, defectos: 1.5},
      %{confeccionista: "C01", linea: "L1", dia: 1,
        prendas: 175, defectos: 1.7},
      %{confeccionista: "C03", linea: "L3", dia: 1,
        prendas: 95, defectos: 3.5},
      %{confeccionista: "C05", linea: "L1", dia: 1,
        prendas: 40, defectos: 0.8},
      %{confeccionista: "C09", linea: "L1", dia: 1,
        prendas: 45, defectos: 2.8},
      %{confeccionista: "C09", linea: "L1", dia: 1,
        prendas: 75, defectos: 3.4},
      %{confeccionista: "C09", linea: "L1", dia: 1,
        prendas: 175, defectos: 0.9},
      %{confeccionista: "C09", linea: "L1", dia: 1,
        prendas: 145, defectos: 2.8},
      %{confeccionista: "C10", linea: "L2", dia: 1,
        prendas: 55, defectos: 9.9},
      %{confeccionista: "C01", linea: "L1", dia: 2,
        prendas: 130, defectos: 3.6},
      %{confeccionista: "C01", linea: "L1", dia: 2,
        prendas: 80, defectos: 2.3},
      %{confeccionista: "C04", linea: "L4", dia: 2,
        prendas: 180, defectos: 7.8},
      %{confeccionista: "C05", linea: "L1", dia: 2,
        prendas: 125, defectos: 3.1},
      %{confeccionista: "C05", linea: "L1", dia: 2,
        prendas: 155, defectos: 2.5},
      %{confeccionista: "C05", linea: "L1", dia: 2,
        prendas: 165, defectos: 2.2},
      %{confeccionista: "C06", linea: "L2", dia: 2,
        prendas: 110, defectos: 9.2},
      %{confeccionista: "C06", linea: "L2", dia: 2,
        prendas: 30, defectos: 100.0},
      %{confeccionista: "C07", linea: "L3", dia: 2,
        prendas: 50, defectos: 1.7},
      %{confeccionista: "C08", linea: "L4", dia: 2,
        prendas: 110, defectos: 8.5},
      %{confeccionista: "C09", linea: "L1", dia: 2,
        prendas: 120, defectos: 3.7},
      %{confeccionista: "C09", linea: "L1", dia: 2,
        prendas: 40, defectos: 0.7},
      %{confeccionista: "C01", linea: "L1", dia: 3,
        prendas: 180, defectos: 0.0},
      %{confeccionista: "C02", linea: "L2", dia: 3,
        prendas: 65, defectos: 6.6},
      %{confeccionista: "C02", linea: "L2", dia: 3,
        prendas: 45, defectos: 5.6},
      %{confeccionista: "C02", linea: "L2", dia: 3,
        prendas: 60, defectos: 9.6},
      %{confeccionista: "C02", linea: "L2", dia: 3,
        prendas: 55, defectos: 8.8},
      %{confeccionista: "C03", linea: "L3", dia: 3,
        prendas: 70, defectos: 2.8},
      %{confeccionista: "C05", linea: "L1", dia: 3,
        prendas: 180, defectos: 3.9},
      %{confeccionista: "C06", linea: "L2", dia: 3,
        prendas: 120, defectos: 8.0},
      %{confeccionista: "C06", linea: "L2", dia: 3,
        prendas: 65, defectos: 5.4},
      %{confeccionista: "C08", linea: "L4", dia: 3,
        prendas: 120, defectos: 6.3},
      %{confeccionista: "C10", linea: "L2", dia: 3,
        prendas: 40, defectos: 11.0},
      %{confeccionista: "C10", linea: "L2", dia: 3,
        prendas: 90, defectos: 6.9},
      %{confeccionista: "C01", linea: "L1", dia: 4,
        prendas: 135, defectos: 0.7},
      %{confeccionista: "C02", linea: "L2", dia: 4,
        prendas: 100, defectos: 8.7},
      %{confeccionista: "C03", linea: "L3", dia: 4,
        prendas: 180, defectos: 3.7},
      %{confeccionista: "C03", linea: "L3", dia: 4,
        prendas: 70, defectos: 2.4},
      %{confeccionista: "C04", linea: "L4", dia: 4,
        prendas: 50, defectos: 6.9},
      %{confeccionista: "C04", linea: "L4", dia: 4,
        prendas: 30, defectos: 5.8},
      %{confeccionista: "C06", linea: "L2", dia: 4,
        prendas: 40, defectos: 8.9},
      %{confeccionista: "C06", linea: "L2", dia: 4,
        prendas: 60, defectos: 5.7},
      %{confeccionista: "C07", linea: "L3", dia: 4,
        prendas: 65, defectos: 2.1},
      %{confeccionista: "C08", linea: "L4", dia: 4,
        prendas: 40, defectos: 11.8},
      %{confeccionista: "C08", linea: "L4", dia: 4,
        prendas: 100, defectos: 11.0},
      %{confeccionista: "C09", linea: "L1", dia: 4,
        prendas: 130, defectos: 1.5},
      %{confeccionista: "C01", linea: "L1", dia: 5,
        prendas: 135, defectos: 1.2},
      %{confeccionista: "C02", linea: "L2", dia: 5,
        prendas: 95, defectos: 11.8},
      %{confeccionista: "C02", linea: "L2", dia: 5,
        prendas: 65, defectos: 6.9},
      %{confeccionista: "C03", linea: "L3", dia: 5,
        prendas: 175, defectos: 3.8},
      %{confeccionista: "C03", linea: "L3", dia: 5,
        prendas: 40, defectos: 2.6},
      %{confeccionista: "C03", linea: "L3", dia: 5,
        prendas: 160, defectos: 3.1},
      %{confeccionista: "C04", linea: "L4", dia: 5,
        prendas: 40, defectos: 9.1},
      %{confeccionista: "C04", linea: "L4", dia: 5,
        prendas: 70, defectos: 10.6},
      %{confeccionista: "C05", linea: "L1", dia: 5,
        prendas: 160, defectos: 1.4},
      %{confeccionista: "C06", linea: "L2", dia: 5,
        prendas: 100, defectos: 5.8},
      %{confeccionista: "C07", linea: "L3", dia: 5,
        prendas: 70, defectos: 3.0},
      %{confeccionista: "C07", linea: "L3", dia: 5,
        prendas: 100, defectos: 1.8},
      %{confeccionista: "C07", linea: "L3", dia: 5,
        prendas: 50, defectos: 0.8},
      %{confeccionista: "C08", linea: "L4", dia: 5,
        prendas: 115, defectos: 6.6},
      %{confeccionista: "C09", linea: "L1", dia: 5,
        prendas: 160, defectos: 0.9},
      %{confeccionista: "C01", linea: "L1", dia: 6,
        prendas: 55, defectos: 0.6},
      %{confeccionista: "C02", linea: "L2", dia: 6,
        prendas: 85, defectos: 6.1},
      %{confeccionista: "C03", linea: "L3", dia: 6,
        prendas: 55, defectos: 2.9},
      %{confeccionista: "C04", linea: "L4", dia: 6,
        prendas: 40, defectos: 9.3},
      %{confeccionista: "C04", linea: "L4", dia: 6,
        prendas: 45, defectos: 9.8},
      %{confeccionista: "C04", linea: "L4", dia: 6,
        prendas: 120, defectos: 9.0},
      %{confeccionista: "C05", linea: "L1", dia: 6,
        prendas: 110, defectos: 2.4},
      %{confeccionista: "C05", linea: "L1", dia: 6,
        prendas: 140, defectos: 1.8},
      %{confeccionista: "C06", linea: "L2", dia: 6,
        prendas: 80, defectos: 5.8},
      %{confeccionista: "C07", linea: "L3", dia: 6,
        prendas: 135, defectos: 3.6},
      %{confeccionista: "C07", linea: "L3", dia: 6,
        prendas: 150, defectos: 2.4},
      %{confeccionista: "C07", linea: "L3", dia: 6,
        prendas: 105, defectos: 1.7},
      %{confeccionista: "C08", linea: "L4", dia: 6,
        prendas: 115, defectos: 7.9},
      %{confeccionista: "C08", linea: "L4", dia: 6,
        prendas: 80, defectos: 10.9},
      %{confeccionista: "C08", linea: "L4", dia: 6,
        prendas: 70, defectos: 0.0},
      %{confeccionista: "C10", linea: "L2", dia: 6,
        prendas: 55, defectos: 10.5},
      %{confeccionista: "C10", linea: "L2", dia: 6,
        prendas: 75, defectos: 10.9},
      %{confeccionista: "C10", linea: "L2", dia: 6,
        prendas: 105, defectos: 11.6},
      %{confeccionista: "C10", linea: "L2", dia: 6,
        prendas: 35, defectos: 6.6},
      %{confeccionista: "C10", linea: "L2", dia: 6,
        prendas: 45, defectos: 5.4}

# lotes inválidos

 %{confeccionista: "C11", linea: "L4", dia: 1,
 prendas: 55, defectos: 7}
  %{confeccionista: "C12", linea: "L4", dia: 1,
 prendas: 55, defectos: 7}
 %{confeccionista: "C08", linea: "L5", dia: 1,
 prendas: 55, defectos: 7}
 %{confeccionista: "C08", linea: "L6", dia: 1,
 prendas: 55, defectos: 7}
  %{confeccionista: "C08", linea: "L5", dia: 7,
 prendas: 55, defectos: 7}
  %{confeccionista: "C08", linea: "L5", dia: 7,
 prendas: 55, defectos: 7}
 %{confeccionista: "C07", linea: "L3", dia: 1,
 prendas: 195, defectos: 1.5},
 %{confeccionista: "C08", linea: "L4", dia: 1,
 prendas: 210, defectos: 7}
 %{confeccionista: "C07", linea: "L3", dia: 1,
 prendas: 70, defectos: -15},
 %{confeccionista: "C08", linea: "L4", dia: 1,
 prendas: 55, defectos: 105}


 ]

 end
end
